language: c
install: wget https://raw.githubusercontent.com/ocaml/ocaml-travisci-skeleton/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
before_install:
  - sudo apt-get update
  - sudo apt-get install -y capnproto libcapnp-dev
env:
  global:
    - ALCOTEST_SHOW_ERRORS=1
    - PINS="irmin.dev:--dev irmin-mem.dev:--dev irmin-fs.dev:--dev irmin-http.dev:--dev irmin-git.dev:--dev irmin-mirage.dev:--dev irmin-unix.dev:--dev  git.dev:--dev git-unix.dev:--dev git-mirage.dev:--dev git-http.dev:--dev digestif.dev:--dev decompress.dev:--dev irmin-rpc.dev:. irmin-rpc-unix.dev:. irmin-rpc-mirage.dev:."
  matrix:
    - OCAML_VERSION=4.06 PACKAGE="irmin-rpc-unix.dev" TESTS=false
    - OCAML_VERSION=4.07 PACKAGE="irmin-rpc-unix.dev" TESTS=false
    - OCAML_VERSION=4.06 PACKAGE="irmin-rpc-mirage.dev" TESTS=false
    - OCAML_VERSION=4.07 PACKAGE="irmin-rpc-mirage.dev" TESTS=false
